# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: postgresql
  user: grangerabuhoff
  host: localhost
  database: apt_broker_db
  pool: 5
  timeout: 5000



production:
  adapter: postgresql
  user: grangerabuhoff
  database: apt_broker_db
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  database: brokr_test
  pool: 5
  username: grangerabuhoff
  host: localhost